### ISSUE TITLE
Exception thrown

### ISSUE THREAD

**Issue by jaszlo** [jaszlo/Playerautoma#24]
Version v0.5.2+11.20.6 0.5.2
So I basically made it as fast as I can and if client I use it on has too little ram and at the same time triggers wrong inventory (example: chest instead of crafting table) it breaks whole minecraft instance
Happens similarly with more ram, but game crashes instead of breaking itself completely.20.6: 
[recording.json](https://github.com/user-attachments/files/17285178/emebloki.copy.json)

Stacktrace
```
---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 2024-10-06 23:36:24
Description: Initializing game

java.lang.NullPointerException: Cannot invoke "net.jasper.mod.util.data.RecordingThumbnail.toNativeImage()" because "r.thumbnail" is null
	at net.jasper.mod.gui.RecordingSelectorScreen.loadThumbnails(RecordingSelectorScreen.java:67)
	at net.jasper.mod.PlayerAutomaClient.initializeAfterClient(PlayerAutomaClient.java:43)
	at net.minecraft.class_310.handler$zng000$playerautoma$injected(class_310.java:6245)
	at net.minecraft.class_310.<init>(class_310.java:712)
	at net.minecraft.client.main.Main.main(Main.java:223)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at crystallauncher.MinecraftConstructor.run(MinecraftConstructor.java:29)
	at crystallauncher.MineClient.start(MineClient.java:201)
	at crystallauncher.MineClient.main(MineClient.java:42)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.jasper.mod.gui.RecordingSelectorScreen.loadThumbnails(RecordingSelectorScreen.java:67)
	at net.jasper.mod.PlayerAutomaClient.initializeAfterClient(PlayerAutomaClient.java:43)
	at net.minecraft.class_310.handler$zng000$playerautoma$injected(class_310.java:6245)
	at net.minecraft.class_310.<init>(class_310.java:712)

-- Initialization --
Details:
```

**Comment by jaszlo** [comment]
Will be patched with next version
